from django.urls import path
from .views import (
    profile,
    plant_list,
    my_requests,
    manage_requests,
    request_collection,
    view_collections,
    create_collection,
    collection_detail,
    upload_image,
    upload_success,
    plant_add,
    plant_edit,
    plant_delete,
    borrow_plant,
    delete_borrow_request,
    approve_request,
    decline_request,
    edit_collection,
    delete_collection,
    collection_detail,
    leave_review,
    delete_review,
    manage_patrons,
    upload_profile_picture,
    request_extension,
)

urlpatterns = [
    path("", plant_list, name="plant_list"),
    path("my-requests/", my_requests, name="my_requests"),
    path("manage-requests/", manage_requests, name="manage_requests"),
    path("view-collections/", view_collections, name="view_collections"),
    path("create-collection/", create_collection, name="create_collection"),
    path("collection/<int:collection_id>/", collection_detail, name="collection_detail"),
    path("upload/", upload_image, name="upload_image"),
    path("upload/success", upload_success, name="upload_success"),
    path("plant_add/", plant_add, name="plant_add"),
    path("plant_edit/<int:pk>/", plant_edit, name="plant_edit"),
    path('plant/<int:pk>/delete/', plant_delete, name='plant_delete'),
    path("<int:plant_id>/borrow", borrow_plant, name="borrow_plant"),
    path("<int:br_id>/delete_request", delete_borrow_request, name="delete_borrow_request"),
    path("<int:br_id>/approve_request", approve_request, name="approve_request"),
    path("<int:br_id>/decline_request", decline_request, name="decline_request"),
    path("collections/edit/<int:collection_id>/", edit_collection, name="edit_collection"),
    path("collections/delete/<int:collection_id>/", delete_collection, name="delete_collection"),
    path("collection/<int:collection_id>/", collection_detail, name="collection_detail"),
    path("plant/<int:plant_id>/leave_review/", leave_review, name="leave_review"),
    path("review/<int:review_id>/delete/", delete_review, name="delete_review"),
    path("request_collection/<int:collection_id>/", request_collection, name="request_collection"),
    path("manage-patrons/", manage_patrons, name="manage_patrons"),
    path("profile", profile, name="profile"),
    path('upload-profile-picture/', upload_profile_picture, name='upload_profile_picture'),
    path('plants/request-extension/<int:br_id>/', request_extension, name='request_extension'),
]
