# Generated by Django 4.2.19 on 2025-04-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_collections_plant_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='plant',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
