# Generated by Django 4.2.19 on 2025-04-10 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0004_rename_reviews_plant_comments_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='requested_users',
            field=models.ManyToManyField(blank=True, related_name='requested_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
