# Generated by Django 4.2.19 on 2025-04-28 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0005_collections_requested_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='price_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_plants', to=settings.AUTH_USER_MODEL),
        ),
    ]
