# Generated by Django 4.2.19 on 2025-04-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_plant_difficulty_plant_price_range_plant_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='price_range',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
