# Generated by Django 4.2.19 on 2025-04-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_alter_plant_price_range_alter_plant_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='description',
        ),
        migrations.AlterField(
            model_name='plant',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price_range',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plant',
            name='size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='temperature_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
