# Generated by Django 4.2.19 on 2025-04-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_remove_species_description_alter_plant_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='location',
            field=models.CharField(blank=True, default='Charolottesville, VA', max_length=100, null=True),
        ),
    ]
