# Generated by Django 4.2.19 on 2025-04-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0008_remove_species_description_alter_plant_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="price_range",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="plant",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plants",
                to="plants.species",
            ),
        ),
    ]
