# Generated by Django 4.2.19 on 2025-04-29 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_borrowrequest_request_date_borrowrequest_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='request_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
