# Generated by Django 4.2.19 on 2025-04-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_plant_price_range_alter_plant_species'),
        ('plants', '0009_plant_location'),
    ]

    operations = [
    ]
