# Generated by Django 4.2.19 on 2025-04-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_alter_borrowrequest_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='extension_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Rejected', 'rejected')], default='PENDING', max_length=10),
        ),
    ]
