# Generated by Django 4.2.19 on 2025-04-29 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_merge_20250429_1608'),
        ('plants', '0012_borrowrequest_extension_granted_and_more'),
    ]

    operations = [
    ]
