# Generated by Django 4.2.19 on 2025-04-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_merge_20250429_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='species',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
    ]
