# Generated by Django 4.2.19 on 2025-04-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_remove_plant_species_delete_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='price_range',
            field=models.CharField(default='Under $20', max_length=20),
        ),
    ]
