# Generated by Django 4.2.19 on 2025-04-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plants", "0015_plant_price_alter_plant_price_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
