# Generated by Django 4.2.19 on 2025-04-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_merge_20250429_2114'),
        ('plants', '0016_alter_borrowrequest_status'),
    ]

    operations = [
    ]
